name: "Main"
on:
  repository_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
 # build-test:
 #   runs-on: ipfs-dev-gateway
 #   name: Build test
 #   steps:
 #     - uses: actions/checkout@v4
 #     - uses: actions/setup-node@v4
 #       with:
 #         node-version: '22'
 #     - run: npx @dappnode/dappnodesdk build github-action build --content_provider=http://10.200.200.7:5001 --skip_save

  # e2e-test:
  #   runs-on: mainnet
  #   needs: build-test
  #   if: github.event_name != 'push'
  #   name: End to end tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: npx @dappnode/dappnodesdk@latest github-action test-end-to-end --errorLogsTimeout 120 --healthCheckUrl http://geth.dappnode:8545 --network mainnet

  release:
    name: Release
    runs-on: ipfs-dev-gateway
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --github_release --content_provider=http://65.108.192.207:5001 -eth_provider=https://web3.dappnode.net --all-variants --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
